# Generated by Django 6.0.7 on 2026-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raast_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
