# Generated by Django 6.0.7 on 2026-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('raast', 'Raast (manual)')], max_length=10),
        ),
    ]
